TEST_DEFINITIONS = {
    # 1. Glycemic / Diabetic Panel
    "fasting_glucose": {
        "label": "Fasting Glucose",
        "unit": "mg/dL",
        "range": (55, 320),
        "ideal": (70, 99),
        "normal_range": "70-99",
        "keywords": [
            "fasting glucose",
            "fasting blood sugar",
            "glucose fasting",
            "blood sugar fasting",
            "blood glucose fasting",
            "glucose",
            "fbs",
            "sugar",
        ],
    },
    "hba1c": {
        "label": "HbA1c",
        "unit": "%",
        "range": (4, 15),
        "ideal": (4.5, 5.6),
        "normal_range": "Below 5.7",
        "keywords": [
            "hba1c",
            "hb a1c",
            "glycated hemoglobin",
            "glycated haemoglobin",
            "glycosylated hemoglobin",
            "glycosylated haemoglobin",
            "a1c",
        ],
    },
    # 2. Lipid Profile
    "total_cholesterol": {
        "label": "Total Cholesterol",
        "unit": "mg/dL",
        "range": (80, 400),
        "ideal": (125, 199),
        "normal_range": "Below 200",
        "keywords": ["total cholesterol", "cholesterol total", "serum cholesterol", "cholesterol", "cholester0l"],
    },
    "ldl": {
        "label": "LDL",
        "unit": "mg/dL",
        "range": (40, 280),
        "ideal": (50, 99),
        "normal_range": "Below 100",
        "keywords": ["ldl", "ld1", "low density lipoprotein", "low-density", "ldl cholesterol"],
    },
    "hdl": {
        "label": "HDL",
        "unit": "mg/dL",
        "range": (20, 120),
        "ideal": (40, 80),
        "normal_range": "40 or higher",
        "keywords": ["hdl", "hd1", "high density lipoprotein", "high-density", "hdl cholesterol"],
    },
    "triglycerides": {
        "label": "Triglycerides",
        "unit": "mg/dL",
        "range": (30, 600),
        "ideal": (50, 149),
        "normal_range": "Below 150",
        "keywords": ["triglycerides", "triglyceride", "triglycerid", "tg", "tri glycerides"],
    },
    # 3. Cardiovascular / Vitals
    "blood_pressure_systolic": {
        "label": "Blood Pressure (Systolic)",
        "unit": "mmHg",
        "range": (80, 220),
        "ideal": (90, 119),
        "normal_range": "Below 120",
        "keywords": ["blood pressure", "bp", "b.p", "systolic", "resting blood pressure", "pressure"],
    },
    "blood_pressure_diastolic": {
        "label": "Blood Pressure (Diastolic)",
        "unit": "mmHg",
        "range": (40, 130),
        "ideal": (60, 79),
        "normal_range": "Below 80",
        "keywords": ["blood pressure", "bp", "b.p", "diastolic", "resting blood pressure", "pressure"],
    },
    # 4. Kidney Function (KFT / RFT)
    "creatinine": {
        "label": "Creatinine",
        "unit": "mg/dL",
        "range": (0.3, 12),
        "ideal": (0.6, 1.3),
        "normal_range": "0.6-1.3",
        "keywords": ["creatinine", "serum creatinine", "creat", "creatinin"],
    },
    "urea": {
        "label": "Blood Urea Nitrogen / Urea",
        "unit": "mg/dL",
        "range": (5, 120),
        "ideal": (7, 20),
        "normal_range": "7-20 (BUN) / 15-45 (Urea)",
        "keywords": ["blood urea nitrogen", "bun", "serum urea", "blood urea", "urea"],
    },
    "uric_acid": {
        "label": "Uric Acid",
        "unit": "mg/dL",
        "range": (1.5, 15),
        "ideal": (3.5, 7.2),
        "normal_range": "3.5-7.2",
        "keywords": ["uric acid", "serum uric acid", "urate"],
    },
    "egfr": {
        "label": "eGFR",
        "unit": "mL/min/1.73m²",
        "range": (10, 150),
        "ideal": (90, 140),
        "normal_range": "90 or higher",
        "keywords": ["egfr", "estimated gfr", "gfr"],
    },
    "sodium": {
        "label": "Sodium (Na+)",
        "unit": "mmol/L",
        "range": (115, 160),
        "ideal": (135, 145),
        "normal_range": "135-145",
        "keywords": ["sodium", "serum sodium", "na+", "na"],
    },
    "potassium": {
        "label": "Potassium (K+)",
        "unit": "mmol/L",
        "range": (2.0, 7.5),
        "ideal": (3.5, 5.0),
        "normal_range": "3.5-5.0",
        "keywords": ["potassium", "serum potassium", "k+", "k"],
    },
    # 5. Liver Function Test (LFT)
    "alt": {
        "label": "ALT (SGPT)",
        "unit": "U/L",
        "range": (3, 500),
        "ideal": (7, 56),
        "normal_range": "7-56",
        "keywords": ["alt", "sgpt", "alanine aminotransferase", "alanine transaminase"],
    },
    "ast": {
        "label": "AST (SGOT)",
        "unit": "U/L",
        "range": (5, 500),
        "ideal": (10, 40),
        "normal_range": "10-40",
        "keywords": ["ast", "sgot", "aspartate aminotransferase", "aspartate transaminase"],
    },
    "alp": {
        "label": "Alkaline Phosphatase (ALP)",
        "unit": "U/L",
        "range": (20, 600),
        "ideal": (44, 147),
        "normal_range": "44-147",
        "keywords": ["alkaline phosphatase", "alp", "alk phos"],
    },
    "total_bilirubin": {
        "label": "Total Bilirubin",
        "unit": "mg/dL",
        "range": (0.1, 20),
        "ideal": (0.1, 1.2),
        "normal_range": "0.1-1.2",
        "keywords": ["total bilirubin", "serum bilirubin", "t.bilirubin", "t bilirubin"],
    },
    "direct_bilirubin": {
        "label": "Direct Bilirubin",
        "unit": "mg/dL",
        "range": (0.0, 10),
        "ideal": (0.0, 0.3),
        "normal_range": "0.0-0.3",
        "keywords": ["direct bilirubin", "conjugated bilirubin", "d.bilirubin"],
    },
    "albumin": {
        "label": "Albumin",
        "unit": "g/dL",
        "range": (1.5, 7.0),
        "ideal": (3.4, 5.4),
        "normal_range": "3.4-5.4",
        "keywords": ["albumin", "serum albumin"],
    },
    "total_protein": {
        "label": "Total Protein",
        "unit": "g/dL",
        "range": (3.5, 12.0),
        "ideal": (6.0, 8.3),
        "normal_range": "6.0-8.3",
        "keywords": ["total protein", "protein total", "serum protein"],
    },
    # 6. Complete Blood Count (CBC) / Hematology
    "hemoglobin": {
        "label": "Hemoglobin",
        "unit": "g/dL",
        "range": (4, 22),
        "ideal": (12, 17.5),
        "normal_range": "12.0-17.5",
        "keywords": ["hemoglobin", "haemoglobin", "hb", "hgb"],
    },
    "wbc": {
        "label": "Total Leukocyte Count (WBC)",
        "unit": "10³/µL",
        "range": (1.0, 50.0),
        "ideal": (4.5, 11.0),
        "normal_range": "4.5-11.0",
        "keywords": ["wbc", "white blood cell", "total leukocyte count", "tlc", "leukocyte count"],
    },
    "platelets": {
        "label": "Platelet Count",
        "unit": "10³/µL",
        "range": (20, 900),
        "ideal": (150, 450),
        "normal_range": "150-450",
        "keywords": ["platelets", "platelet count", "plt", "thrombocyte count"],
    },
    "rbc": {
        "label": "RBC Count",
        "unit": "10⁶/µL",
        "range": (2.0, 8.0),
        "ideal": (4.2, 5.9),
        "normal_range": "4.2-5.9",
        "keywords": ["rbc", "red blood cell", "red cell count", "total rbc"],
    },
    "hematocrit": {
        "label": "Hematocrit (PCV)",
        "unit": "%",
        "range": (20, 65),
        "ideal": (37, 52),
        "normal_range": "37-52",
        "keywords": ["hematocrit", "haematocrit", "pcv", "packed cell volume", "hct"],
    },
    "esr": {
        "label": "ESR",
        "unit": "mm/hr",
        "range": (0, 120),
        "ideal": (0, 20),
        "normal_range": "0-20",
        "keywords": ["esr", "erythrocyte sedimentation rate", "sed rate"],
    },
    # 7. Thyroid Profile
    "tsh": {
        "label": "TSH",
        "unit": "µIU/mL",
        "range": (0.01, 50.0),
        "ideal": (0.45, 4.5),
        "normal_range": "0.45-4.5",
        "keywords": ["tsh", "thyroid stimulating hormone", "thyrotropin"],
    },
    "free_t3": {
        "label": "Free T3",
        "unit": "pg/mL",
        "range": (0.5, 12.0),
        "ideal": (2.0, 4.4),
        "normal_range": "2.0-4.4",
        "keywords": ["free t3", "ft3", "triiodothyronine free"],
    },
    "free_t4": {
        "label": "Free T4",
        "unit": "ng/dL",
        "range": (0.1, 6.0),
        "ideal": (0.8, 1.8),
        "normal_range": "0.8-1.8",
        "keywords": ["free t4", "ft4", "thyroxine free"],
    },
    # 8. Vitamin & Mineral Profile
    "vitamin_d": {
        "label": "Vitamin D (25-OH)",
        "unit": "ng/mL",
        "range": (4, 150),
        "ideal": (30, 100),
        "normal_range": "30-100",
        "keywords": ["vitamin d", "25-oh vitamin d", "25 hydroxyvitamin d", "vit d"],
    },
    "vitamin_b12": {
        "label": "Vitamin B12",
        "unit": "pg/mL",
        "range": (50, 2000),
        "ideal": (200, 900),
        "normal_range": "200-900",
        "keywords": ["vitamin b12", "vit b12", "cobalamin", "b12"],
    },
    "calcium": {
        "label": "Serum Calcium",
        "unit": "mg/dL",
        "range": (5.0, 16.0),
        "ideal": (8.5, 10.5),
        "normal_range": "8.5-10.5",
        "keywords": ["calcium", "serum calcium", "ca"],
    },
    "iron": {
        "label": "Serum Iron",
        "unit": "µg/dL",
        "range": (20, 300),
        "ideal": (60, 170),
        "normal_range": "60-170",
        "keywords": ["serum iron", "total iron", "iron"],
    },
    "ferritin": {
        "label": "Serum Ferritin",
        "unit": "ng/mL",
        "range": (5, 800),
        "ideal": (20, 250),
        "normal_range": "20-250",
        "keywords": ["ferritin", "serum ferritin"],
    },
    # 9. Inflammatory Profile
    "hscrp": {
        "label": "hs-CRP",
        "unit": "mg/L",
        "range": (0.1, 50.0),
        "ideal": (0.0, 1.0),
        "normal_range": "Below 1.0",
        "keywords": ["hscrp", "hs-crp", "c-reactive protein", "crp", "high sensitivity crp"],
    },
}

DISPLAY_TEST_ORDER = [
    # Glycemic
    "fasting_glucose",
    "hba1c",
    # Lipid
    "total_cholesterol",
    "ldl",
    "hdl",
    "triglycerides",
    # Vitals
    "blood_pressure",
    # Kidney
    "creatinine",
    "urea",
    "uric_acid",
    "egfr",
    "sodium",
    "potassium",
    # Liver
    "alt",
    "ast",
    "alp",
    "total_bilirubin",
    "direct_bilirubin",
    "albumin",
    "total_protein",
    # Hematology
    "hemoglobin",
    "wbc",
    "platelets",
    "rbc",
    "hematocrit",
    "esr",
    # Thyroid
    "tsh",
    "free_t3",
    "free_t4",
    # Vitamins
    "vitamin_d",
    "vitamin_b12",
    "calcium",
    "iron",
    "ferritin",
    # Inflammation
    "hscrp",
]

REPORT_TYPE_KEYWORDS = {
    "Lipid Profile": ["lipid profile", "cholesterol", "triglycerides", "hdl", "ldl"],
    "Blood Sugar Report": ["blood sugar", "fasting glucose", "glucose fasting", "hba1c", "glycated hemoglobin", "fbs"],
    "Kidney Function Report": ["creatinine", "renal profile", "kidney function", "rft", "serum creatinine", "urea", "uric acid"],
    "Liver Function Test": ["liver function", "lft", "sgpt", "sgot", "alt", "ast", "bilirubin", "alkaline phosphatase"],
    "Complete Blood Count": ["complete blood count", "cbc", "hematology", "hemoglobin", "wbc", "platelets", "tlc"],
    "Thyroid Profile": ["thyroid profile", "tsh", "free t3", "free t4", "thyroid function"],
    "Vitamin & Deficiency Panel": ["vitamin d", "vitamin b12", "ferritin", "iron", "calcium"],
    "Inflammatory Panel": ["hscrp", "c-reactive protein", "esr"],
}

RISK_ORDER = {"unknown": -1, "low": 0, "moderate": 1, "high": 2}
RISK_LABELS = {
    "unknown": "Unable to Predict",
    "low": "Low Risk",
    "moderate": "Moderate Risk",
    "high": "High Risk",
}

CARDIO_MODEL_FEATURES = ["age", "sex", "trestbps", "chol", "fbs"]
CARDIO_MODEL_FEATURE_LABELS = {
    "age": "Age",
    "sex": "Sex",
    "trestbps": "Resting Blood Pressure",
    "chol": "Total Cholesterol",
    "fbs": "Fasting Blood Sugar Flag",
}

PII_COLUMN_HINTS = [
    "name",
    "address",
    "phone",
    "email",
    "hospital_id",
    "hospitalid",
    "patient_id",
    "patientid",
    "aadhaar",
    "aadhar",
    "ssn",
    "social_security",
    "socialsecurity",
    "report_number",
    "reportnumber",
    "barcode",
    "signature",
    "id",
    "ccf",
]

PRIVACY_NOTICE = (
    "Uploaded reports are processed transiently for extraction and scoring only. "
    "The original file is deleted immediately after analysis, and no personal identifiers are persisted."
)
